#!/bin/bash

if [ $# -eq 0 ]; then

todo="residual"

else

todo=$1

fi

if [ $todo = "residual" ]; then
gnuplot convergence.plt
fi

if [ $todo = "2D" ]; then
gnuplot loads2D.plt 2&> /dev/null
gnuplot movement2D.plt 2&> /dev/null
python xCp2D.py
fi

if [ $todo = "3D" ]; then
gnuplot loads3D.plt 2&> /dev/null
gnuplot modal3D.plt 2&> /dev/null
echo "Press return to export current image into deform3D.eps file..."
python xyCp3D.py
fi
